name: hotak-ai-venv
channels:
  - defaults
dependencies:
  - langchain-ollama
  - langchain
  - fastapi
  - langchain-chroma
  - python=3.12
  - uvicorn
  - langchain-text-splitters
  - beautifulsoup4
  - langchain-community
  - python-dotenv
  - pypdf
  - langchain-openai
prefix: C:\Users\User\miniconda3\envs\hotak-ai-venv
