name: hotak-ai-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - langchain
  - langchain-community
  - langchain-ollama
  - langchain-chroma
  - langchain-text-splitters
  - beautifulsoup4
